package main

import (
	"PilEk/db"
	_ "PilEk/docs" // docs is generated by Swag CLI, you have to import it.
	"PilEk/handler"
	"PilEk/router"
	"PilEk/store"
)

func main() {
	r := router.New()

	r.Static("/", "dist")
	v1 := r.Group("/api")

	d := db.New()
	db.AutoMigrate(d)

	us := store.NewUserStore(d)
	as := store.NewKandidatStore(d)
	fs := store.NewKelasStore(d)

	h := handler.NewHandler(*us, *as, *fs)
	h.Register(v1)
	r.Logger.Error(r.Start(":8585"))
}
